//
//  SupportedMazes.m
//  CS-440-Maze-Search
//
//  Created by Troy Chmieleski on 9/23/13.
//  Copyright (c) 2013 Troy Chmieleski. All rights reserved.
//

#import "SupportedMazes.h"

NSArray * SupportedMazes() {
	return @[SUPPORTED_MAZE_SMALL_MAZE_FILENAME, SUPPORTED_MAZE_MEDIUM_MAZE_FILENAME, SUPPORTED_MAZE_BIG_MAZE_FILENAME, SUPPORTED_MAZE_OPEN_MAZE_FILENAME, SUPPORTED_MAZE_TINY_SEARCH_FILENAME, SUPPORTED_MAZE_SMALL_SEARCH_FILENAME, SUPPORTED_MAZE_MEDIUM_SEARCH_FILENAME, SUPPORTED_MAZE_BIG_SEARCH_FILENAME, SUPPORTED_MAZE_TRICKY_SEARCH_FILENAME];
}

NSArray * SupportedMazeNames() {
	return @[SUPPORTED_MAZE_SMALL_MAZE_NAME, SUPPORTED_MAZE_MEDIUM_MAZE_NAME, SUPPORTED_MAZE_BIG_MAZE_NAME, SUPPORTED_MAZE_OPEN_MAZE_NAME, SUPPORTED_MAZE_TINY_SEARCH_NAME, SUPPORTED_MAZE_SMALL_SEARCH_NAME, SUPPORTED_MAZE_MEDIUM_SEARCH_NAME, SUPPORTED_MAZE_BIG_SEARCH_NAME, SUPPORTED_MAZE_TRICKY_SEARCH_NAME];
}